<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class GiangVienSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            [
                'ho_va_ten' => 'PGS.TS Nguyễn Văn Anh',
                'ma_giang_vien' => 'GV001',
                'email' => 'nguyenvananh@edu.vn',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0912345671',
                'thong_tin_chung' => 'Giảng viên khoa Công nghệ thông tin, chuyên ngành Trí tuệ nhân tạo',
                'anh_dai_dien' => '/assets/images/avatars/avatar-1.png',
                'trang_thai' => 1,
            ],
            [
                'ho_va_ten' => 'TS. Trần Thị Bích',
                'ma_giang_vien' => 'GV002',
                'email' => 'tranthibich@edu.vn',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0912345672',
                'thong_tin_chung' => 'Giảng viên khoa Kinh tế, chuyên ngành Tài chính ngân hàng',
                'anh_dai_dien' => '/assets/images/avatars/avatar-2.png',
                'trang_thai' => 1,
            ],
            [
                'ho_va_ten' => 'PGS.TS Lê Văn Cương',
                'ma_giang_vien' => 'GV003',
                'email' => 'levancuong@edu.vn',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0912345673',
                'thong_tin_chung' => 'Giảng viên khoa Cơ khí, chuyên ngành Cơ điện tử',
                'anh_dai_dien' => '/assets/images/avatars/avatar-3.png',
                'trang_thai' => 1,
            ],
            [
                'ho_va_ten' => 'TS. Phạm Thị Diệu',
                'ma_giang_vien' => 'GV004',
                'email' => 'phamthidieu@edu.vn',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0912345674',
                'thong_tin_chung' => 'Giảng viên khoa Điện tử, chuyên ngành Vi mạch',
                'anh_dai_dien' => '/assets/images/avatars/avatar-4.png',
                'trang_thai' => 1,
            ],
            [
                'ho_va_ten' => 'PGS.TS Hoàng Văn Đức',
                'ma_giang_vien' => 'GV005',
                'email' => 'hoangvanduc@edu.vn',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0912345675',
                'thong_tin_chung' => 'Giảng viên khoa Xây dựng, chuyên ngành Kết cấu',
                'anh_dai_dien' => '/assets/images/avatars/avatar-5.png',
                'trang_thai' => 0,
            ],
            [
                'ho_va_ten' => 'TS. Ngô Thị Phúc',
                'ma_giang_vien' => 'GV006',
                'email' => 'ngothiphuc@edu.vn',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0912345676',
                'thong_tin_chung' => 'Giảng viên khoa Môi trường, chuyên ngành Công nghệ môi trường',
                'anh_dai_dien' => '/assets/images/avatars/avatar-6.png',
                'trang_thai' => 1,
            ],
            [
                'ho_va_ten' => 'PGS.TS Đỗ Văn Giang',
                'ma_giang_vien' => 'GV007',
                'email' => 'dovangiang@edu.vn',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0912345677',
                'thong_tin_chung' => 'Giảng viên khoa Tự động hóa, chuyên ngành Điều khiển tự động',
                'anh_dai_dien' => '/assets/images/avatars/avatar-7.png',
                'trang_thai' => 1,
            ],
            [
                'ho_va_ten' => 'TS. Vũ Thị Hương',
                'ma_giang_vien' => 'GV008',
                'email' => 'vuthihuong@edu.vn',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0912345678',
                'thong_tin_chung' => 'Giảng viên khoa Công nghệ sinh học, chuyên ngành Vi sinh',
                'anh_dai_dien' => '/assets/images/avatars/avatar-8.png',
                'trang_thai' => 1,
            ],
            [
                'ho_va_ten' => 'PGS.TS Đinh Văn Hiếu',
                'ma_giang_vien' => 'GV009',
                'email' => 'dinhvanhieu@edu.vn',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0912345679',
                'thong_tin_chung' => 'Giảng viên khoa Quản trị kinh doanh, chuyên ngành Quản trị nhân sự',
                'anh_dai_dien' => '/assets/images/avatars/avatar-9.png',
                'trang_thai' => 0,
            ],
            [
                'ho_va_ten' => 'TS. Bùi Thị Khánh',
                'ma_giang_vien' => 'GV010',
                'email' => 'buithikhanh@edu.vn',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0912345680',
                'thong_tin_chung' => 'Giảng viên khoa Marketing, chuyên ngành Digital Marketing',
                'anh_dai_dien' => '/assets/images/avatars/avatar-10.png',
                'trang_thai' => 1,
            ],
            [
                'ho_va_ten' => 'PGS.TS Lý Văn Linh',
                'ma_giang_vien' => 'GV011',
                'email' => 'lyvanlinh@edu.vn',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0912345681',
                'thong_tin_chung' => 'Giảng viên khoa Luật, chuyên ngành Luật kinh tế',
                'anh_dai_dien' => '/assets/images/avatars/avatar-1.png',
                'trang_thai' => 1,
            ],
            [
                'ho_va_ten' => 'TS. Mai Thị Mai',
                'ma_giang_vien' => 'GV012',
                'email' => 'maithimai@edu.vn',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0912345682',
                'thong_tin_chung' => 'Giảng viên khoa Ngôn ngữ Anh, chuyên ngành Biên-Phiên dịch',
                'anh_dai_dien' => '/assets/images/avatars/avatar-2.png',
                'trang_thai' => 1,
            ],
            [
                'ho_va_ten' => 'PGS.TS Trương Văn Nam',
                'ma_giang_vien' => 'GV013',
                'email' => 'truongvannam@edu.vn',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0912345683',
                'thong_tin_chung' => 'Giảng viên khoa Công nghệ thông tin, chuyên ngành An toàn thông tin',
                'anh_dai_dien' => '/assets/images/avatars/avatar-3.png',
                'trang_thai' => 0,
            ],
            [
                'ho_va_ten' => 'TS. Phan Thị Oanh',
                'ma_giang_vien' => 'GV014',
                'email' => 'phanthioanh@edu.vn',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0912345684',
                'thong_tin_chung' => 'Giảng viên khoa Kinh tế, chuyên ngành Kế toán',
                'anh_dai_dien' => '/assets/images/avatars/avatar-4.png',
                'trang_thai' => 1,
            ],
            [
                'ho_va_ten' => 'PGS.TS Đặng Văn Phong',
                'ma_giang_vien' => 'GV015',
                'email' => 'dangvanphong@edu.vn',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0912345685',
                'thong_tin_chung' => 'Giảng viên khoa Cơ khí, chuyên ngành Cơ khí chế tạo',
                'anh_dai_dien' => '/assets/images/avatars/avatar-5.png',
                'trang_thai' => 1,
            ],
            [
                'ho_va_ten' => 'TS. Hồ Thị Quỳnh',
                'ma_giang_vien' => 'GV016',
                'email' => 'hothiquynh@edu.vn',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0912345686',
                'thong_tin_chung' => 'Giảng viên khoa Điện tử, chuyên ngành IoT',
                'anh_dai_dien' => '/assets/images/avatars/avatar-6.png',
                'trang_thai' => 1,
            ],
            [
                'ho_va_ten' => 'PGS.TS Lại Văn Rân',
                'ma_giang_vien' => 'GV017',
                'email' => 'laivanran@edu.vn',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0912345687',
                'thong_tin_chung' => 'Giảng viên khoa Xây dựng, chuyên ngành Quản lý dự án',
                'anh_dai_dien' => '/assets/images/avatars/avatar-7.png',
                'trang_thai' => 0,
            ],
            [
                'ho_va_ten' => 'TS. Dương Thị Sen',
                'ma_giang_vien' => 'GV018',
                'email' => 'duongthisen@edu.vn',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0912345688',
                'thong_tin_chung' => 'Giảng viên khoa Môi trường, chuyên ngành Quản lý môi trường',
                'anh_dai_dien' => '/assets/images/avatars/avatar-8.png',
                'trang_thai' => 1,
            ],
            [
                'ho_va_ten' => 'PGS.TS Tống Văn Thành',
                'ma_giang_vien' => 'GV019',
                'email' => 'tongvanthanh@edu.vn',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0912345689',
                'thong_tin_chung' => 'Giảng viên khoa Tự động hóa, chuyên ngành Robot công nghiệp',
                'anh_dai_dien' => '/assets/images/avatars/avatar-9.png',
                'trang_thai' => 1,
            ],
            [
                'ho_va_ten' => 'TS. Lương Thị Uyên',
                'ma_giang_vien' => 'GV020',
                'email' => 'luongthiuyen@edu.vn',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0912345690',
                'thong_tin_chung' => 'Giảng viên khoa Công nghệ sinh học, chuyên ngành Sinh học phân tử',
                'anh_dai_dien' => '/assets/images/avatars/avatar-10.png',
                'trang_thai' => 1,
            ],
        ];

        DB::table('giang_viens')->delete();
        DB::table('giang_viens')->truncate();
        DB::table('giang_viens')->insert($data);
    }
}
