<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class SinhVienSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            [
                'ho_va_ten' => 'Nguyễn Văn An',
                'ma_sinh_vien' => 'SV001',
                'email' => 'nguyenvanan@gmail.com',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0901234567',
                'thong_tin_chung' => 'Sinh viên khoa Công nghệ thông tin',
                'anh_dai_dien' => '/assets/images/avatars/avatar-1.png',
                'trang_thai' => 1,
            ],
            [
                'ho_va_ten' => 'Trần Thị Bình',
                'ma_sinh_vien' => 'SV002',
                'email' => 'tranthibinh@gmail.com',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0901234568',
                'thong_tin_chung' => 'Sinh viên khoa Kinh tế',
                'anh_dai_dien' => '/assets/images/avatars/avatar-2.png',
                'trang_thai' => 1,
            ],
            [
                'ho_va_ten' => 'Lê Văn Cường',
                'ma_sinh_vien' => 'SV003',
                'email' => 'levancuong@gmail.com',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0901234569',
                'thong_tin_chung' => 'Sinh viên khoa Cơ khí',
                'anh_dai_dien' => '/assets/images/avatars/avatar-3.png',
                'trang_thai' => 1,
            ],
            [
                'ho_va_ten' => 'Phạm Thị Dung',
                'ma_sinh_vien' => 'SV004',
                'email' => 'phamthidung@gmail.com',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0901234570',
                'thong_tin_chung' => 'Sinh viên khoa Điện tử',
                'anh_dai_dien' => '/assets/images/avatars/avatar-4.png',
                'trang_thai' => 1,
            ],
            [
                'ho_va_ten' => 'Hoàng Văn Em',
                'ma_sinh_vien' => 'SV005',
                'email' => 'hoangvanem@gmail.com',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0901234571',
                'thong_tin_chung' => 'Sinh viên khoa Xây dựng',
                'anh_dai_dien' => '/assets/images/avatars/avatar-5.png',
                'trang_thai' => 0,
            ],
            [
                'ho_va_ten' => 'Ngô Thị Phương',
                'ma_sinh_vien' => 'SV006',
                'email' => 'ngothiphuong@gmail.com',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0901234572',
                'thong_tin_chung' => 'Sinh viên khoa Môi trường',
                'anh_dai_dien' => '/assets/images/avatars/avatar-6.png',
                'trang_thai' => 1,
            ],
            [
                'ho_va_ten' => 'Đỗ Văn Giang',
                'ma_sinh_vien' => 'SV007',
                'email' => 'dovangiang@gmail.com',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0901234573',
                'thong_tin_chung' => 'Sinh viên khoa Tự động hóa',
                'anh_dai_dien' => '/assets/images/avatars/avatar-7.png',
                'trang_thai' => 1,
            ],
            [
                'ho_va_ten' => 'Vũ Thị Hoa',
                'ma_sinh_vien' => 'SV008',
                'email' => 'vuthihoa@gmail.com',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0901234574',
                'thong_tin_chung' => 'Sinh viên khoa Công nghệ sinh học',
                'anh_dai_dien' => '/assets/images/avatars/avatar-8.png',
                'trang_thai' => 1,
            ],
            [
                'ho_va_ten' => 'Đinh Văn Inh',
                'ma_sinh_vien' => 'SV009',
                'email' => 'dinhvaninh@gmail.com',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0901234575',
                'thong_tin_chung' => 'Sinh viên khoa Quản trị kinh doanh',
                'anh_dai_dien' => '/assets/images/avatars/avatar-9.png',
                'trang_thai' => 0,
            ],
            [
                'ho_va_ten' => 'Bùi Thị Kim',
                'ma_sinh_vien' => 'SV010',
                'email' => 'buithikim@gmail.com',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0901234576',
                'thong_tin_chung' => 'Sinh viên khoa Marketing',
                'anh_dai_dien' => '/assets/images/avatars/avatar-10.png',
                'trang_thai' => 1,
            ],
            [
                'ho_va_ten' => 'Lý Văn Long',
                'ma_sinh_vien' => 'SV011',
                'email' => 'lyvanlong@gmail.com',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0901234577',
                'thong_tin_chung' => 'Sinh viên khoa Luật',
                'anh_dai_dien' => '/assets/images/avatars/avatar-1.png',
                'trang_thai' => 1,
            ],
            [
                'ho_va_ten' => 'Mai Thị Minh',
                'ma_sinh_vien' => 'SV012',
                'email' => 'maithiminh@gmail.com',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0901234578',
                'thong_tin_chung' => 'Sinh viên khoa Ngôn ngữ Anh',
                'anh_dai_dien' => '/assets/images/avatars/avatar-2.png',
                'trang_thai' => 1,
            ],
            [
                'ho_va_ten' => 'Trương Văn Nam',
                'ma_sinh_vien' => 'SV013',
                'email' => 'truongvannam@gmail.com',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0901234579',
                'thong_tin_chung' => 'Sinh viên khoa Công nghệ thông tin',
                'anh_dai_dien' => '/assets/images/avatars/avatar-3.png',
                'trang_thai' => 0,
            ],
            [
                'ho_va_ten' => 'Phan Thị Oanh',
                'ma_sinh_vien' => 'SV014',
                'email' => 'phanthioanh@gmail.com',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0901234580',
                'thong_tin_chung' => 'Sinh viên khoa Kinh tế',
                'anh_dai_dien' => '/assets/images/avatars/avatar-4.png',
                'trang_thai' => 1,
            ],
            [
                'ho_va_ten' => 'Đặng Văn Phúc',
                'ma_sinh_vien' => 'SV015',
                'email' => 'dangvanphuc@gmail.com',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0901234581',
                'thong_tin_chung' => 'Sinh viên khoa Cơ khí',
                'anh_dai_dien' => '/assets/images/avatars/avatar-5.png',
                'trang_thai' => 1,
            ],
            [
                'ho_va_ten' => 'Hồ Thị Quỳnh',
                'ma_sinh_vien' => 'SV016',
                'email' => 'hothiquynh@gmail.com',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0901234582',
                'thong_tin_chung' => 'Sinh viên khoa Điện tử',
                'anh_dai_dien' => '/assets/images/avatars/avatar-6.png',
                'trang_thai' => 1,
            ],
            [
                'ho_va_ten' => 'Lại Văn Rồng',
                'ma_sinh_vien' => 'SV017',
                'email' => 'laivanrong@gmail.com',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0901234583',
                'thong_tin_chung' => 'Sinh viên khoa Xây dựng',
                'anh_dai_dien' => '/assets/images/avatars/avatar-7.png',
                'trang_thai' => 0,
            ],
            [
                'ho_va_ten' => 'Dương Thị Sương',
                'ma_sinh_vien' => 'SV018',
                'email' => 'duongthisuong@gmail.com',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0901234584',
                'thong_tin_chung' => 'Sinh viên khoa Môi trường',
                'anh_dai_dien' => '/assets/images/avatars/avatar-8.png',
                'trang_thai' => 1,
            ],
            [
                'ho_va_ten' => 'Tống Văn Tài',
                'ma_sinh_vien' => 'SV019',
                'email' => 'tongvantai@gmail.com',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0901234585',
                'thong_tin_chung' => 'Sinh viên khoa Tự động hóa',
                'anh_dai_dien' => '/assets/images/avatars/avatar-9.png',
                'trang_thai' => 1,
            ],
            [
                'ho_va_ten' => 'Lương Thị Uyên',
                'ma_sinh_vien' => 'SV020',
                'email' => 'luongthiuyen@gmail.com',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0901234586',
                'thong_tin_chung' => 'Sinh viên khoa Công nghệ sinh học',
                'anh_dai_dien' => '/assets/images/avatars/avatar-10.png',
                'trang_thai' => 1,
            ],
        ];

        DB::table('sinh_viens')->delete();
        DB::table('sinh_viens')->truncate();
        DB::table('sinh_viens')->insert($data);
    }
}
