<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class SinhVienSeeding extends Seeder
{
    public function run()
    {
        DB::table('sinh_viens')->delete();
        DB::table('sinh_viens')->truncate();
        DB::table('sinh_viens')->insert([
            [
                'ho_va_ten' => 'Nguyễn Văn A',
                'can_cuoc' => '049234567893',
                'ma_sinh_vien' => 'SV0001',
                'email' => 'nguyenvana@example.com',
                'password' => Hash::make('88888888'),
                'so_dien_thoai' => '0976987635',
                'thong_tin_chung' => 'Ngành Công nghệ thông tin',
                'anh_dai_dien' => 'https://mighty.tools/mockmind-api/content/human/112.jpg',
                'khoa_id' => 1,
                'trang_thai' => 1,
            ],
            [
                'ho_va_ten' => 'Trần Thị B',
                'can_cuoc' => '023594503954',
                'ma_sinh_vien' => 'SV0002',
                'email' => 'tranthib@example.com',
                'password' => Hash::make('88888888'),
                'so_dien_thoai' => '0987654321',
                'thong_tin_chung' => 'Ngành Kinh tế',
                'anh_dai_dien' => 'https://mighty.tools/mockmind-api/content/human/129.jpg',
                'khoa_id' => 3,
                'trang_thai' => 1,
            ],
            [
                'ho_va_ten' => 'Lê Văn C',
                'can_cuoc' => '046789123742',
                'ma_sinh_vien' => 'SV0003',
                'email' => 'levanc@example.com',
                'password' => Hash::make('88888888'),
                'so_dien_thoai' => '0356789123',
                'thong_tin_chung' => 'Ngành Kỹ thuật cơ khí',
                'anh_dai_dien' => 'https://mighty.tools/mockmind-api/content/human/104.jpg',
                'khoa_id' => 2,
                'trang_thai' => 1,
            ],
            [
                'ho_va_ten' => 'Phạm Thị D',
                'can_cuoc' => '093456789123',
                'ma_sinh_vien' => 'SV0004',
                'email' => 'phamthid@example.com',
                'password' => Hash::make('88888888'),
                'so_dien_thoai' => '0765432198',
                'thong_tin_chung' => 'Ngành Y dược',
                'anh_dai_dien' => 'https://mighty.tools/mockmind-api/content/human/105.jpg',
                'khoa_id' => 4,
                'trang_thai' => 1,
            ],
            [
                'ho_va_ten' => 'Hoàng Văn E',
                'can_cuoc' => '022345678912',
                'ma_sinh_vien' => 'SV0005',
                'email' => 'hoangvane@example.com',
                'password' => Hash::make('88888888'),
                'so_dien_thoai' => '0743219876',
                'thong_tin_chung' => 'Ngành Quản trị kinh doanh',
                'anh_dai_dien' => 'https://mighty.tools/mockmind-api/content/human/102.jpg',
                'khoa_id' => 5,
                'trang_thai' => 1,
            ],
            [
                'ho_va_ten' => 'Vũ Thị F',
                'can_cuoc' => '034567891237',
                'ma_sinh_vien' => 'SV0006',
                'email' => 'vuthif@example.com',
                'password' => Hash::make('88888888'),
                'so_dien_thoai' => '0912345678',
                'thong_tin_chung' => 'Ngành Sư phạm',
                'anh_dai_dien' => 'https://mighty.tools/mockmind-api/content/human/106.jpg',
                'khoa_id' => 3,
                'trang_thai' => 1,
            ],
            [
                'ho_va_ten' => 'Đặng Văn G',
                'can_cuoc' => '019439584278',
                'ma_sinh_vien' => 'SV0007',
                'email' => 'dangvang@example.com',
                'password' => Hash::make('88888888'),
                'so_dien_thoai' => '0923456789',
                'thong_tin_chung' => 'Ngành Luật',
                'anh_dai_dien' => 'https://mighty.tools/mockmind-api/content/human/107.jpg',
                'khoa_id' => 5,
                'trang_thai' => 1,
            ],
            [
                'ho_va_ten' => 'Phan Thị H',
                'can_cuoc' => '033647839367',
                'ma_sinh_vien' => 'SV0008',
                'email' => 'phanthih@example.com',
                'password' => Hash::make('88888888'),
                'so_dien_thoai' => '0934567890',
                'thong_tin_chung' => 'Ngành Báo chí',
                'anh_dai_dien' => 'https://mighty.tools/mockmind-api/content/human/108.jpg',
                'khoa_id' => 2,
                'trang_thai' => 1,
            ],
            [
                'ho_va_ten' => 'Nguyễn Thị I',
                'can_cuoc' => '034598463962',
                'ma_sinh_vien' => 'SV0009',
                'email' => 'nguyenthii@example.com',
                'password' => Hash::make('88888888'),
                'so_dien_thoai' => '0945678901',
                'thong_tin_chung' => 'Ngành Công nghệ sinh học',
                'anh_dai_dien' => 'https://mighty.tools/mockmind-api/content/human/109.jpg',
                'khoa_id' => 4,
                'trang_thai' => 1,
            ],
            [
                'ho_va_ten' => 'Trần Văn J',
                'can_cuoc' => '056337594539',
                'ma_sinh_vien' => 'SV0010',
                'email' => 'tranvanj@example.com',
                'password' => Hash::make('88888888'),
                'so_dien_thoai' => '0956789012',
                'thong_tin_chung' => 'Ngành Kỹ thuật điện',
                'anh_dai_dien' => 'https://mighty.tools/mockmind-api/content/human/110.jpg',
                'khoa_id' => 1,
                'trang_thai' => 1,
            ],
            [
                'ho_va_ten' => 'Lê Thị K',
                'can_cuoc' => '049458427748',
                'ma_sinh_vien' => 'SV0011',
                'email' => 'lethik@example.com',
                'password' => Hash::make('88888888'),
                'so_dien_thoai' => '0967890123',
                'thong_tin_chung' => 'Ngành Tài chính ngân hàng',
                'anh_dai_dien' => 'https://mighty.tools/mockmind-api/content/human/111.jpg',
                'khoa_id' => 3,
                'trang_thai' => 1,
            ],
            [
                'ho_va_ten' => 'Phạm Văn L',
                'can_cuoc' => '036774932448',
                'ma_sinh_vien' => 'SV0012',
                'email' => 'phamvanl@example.com',
                'password' => Hash::make('88888888'),
                'so_dien_thoai' => '0978901234',
                'thong_tin_chung' => 'Ngành Khoa học môi trường',
                'anh_dai_dien' => 'https://mighty.tools/mockmind-api/content/human/112.jpg',
                'khoa_id' => 2,
                'trang_thai' => 1,
            ],
            [
                'ho_va_ten' => 'Hoàng Thị M',
                'can_cuoc' => '045688453287',
                'ma_sinh_vien' => 'SV0013',
                'email' => 'hoangthim@example.com',
                'password' => Hash::make('88888888'),
                'so_dien_thoai' => '0989012345',
                'thong_tin_chung' => 'Ngành Du lịch',
                'anh_dai_dien' => 'https://mighty.tools/mockmind-api/content/human/113.jpg',
                'khoa_id' => 4,
                'trang_thai' => 1,
            ],
            [
                'ho_va_ten' => 'Vũ Văn N',
                'can_cuoc' => '044475538463',
                'ma_sinh_vien' => 'SV0014',
                'email' => 'vuvann@example.com',
                'password' => Hash::make('88888888'),
                'so_dien_thoai' => '0990123456',
                'thong_tin_chung' => 'Ngành Công nghệ thực phẩm',
                'anh_dai_dien' => 'https://mighty.tools/mockmind-api/content/human/114.jpg',
                'khoa_id' => 5,
                'trang_thai' => 1,
            ],
            [
                'ho_va_ten' => 'Đặng Thị O',
                'can_cuoc' => '077357856423',
                'ma_sinh_vien' => 'SV0015',
                'email' => 'dangthio@example.com',
                'password' => Hash::make('88888888'),
                'so_dien_thoai' => '0901234567',
                'thong_tin_chung' => 'Ngành Thiết kế đồ họa',
                'anh_dai_dien' => 'https://mighty.tools/mockmind-api/content/human/115.jpg',
                'khoa_id' => 1,
                'trang_thai' => 1,
            ],
            [
                'ho_va_ten' => 'Phan Văn P',
                'can_cuoc' => '075678934567',
                'ma_sinh_vien' => 'SV0016',
                'email' => 'phanvanp@example.com',
                'password' => Hash::make('88888888'),
                'so_dien_thoai' => '0912345678',
                'thong_tin_chung' => 'Ngành Công nghệ ô tô',
                'anh_dai_dien' => 'https://mighty.tools/mockmind-api/content/human/116.jpg',
                'khoa_id' => 2,
                'trang_thai' => 1,
            ],
            [
                'ho_va_ten' => 'Nguyễn Thị Q',
                'can_cuoc' => '046794279214',
                'ma_sinh_vien' => 'SV0017',
                'email' => 'nguyenthq@example.com',
                'password' => Hash::make('88888888'),
                'so_dien_thoai' => '0923456789',
                'thong_tin_chung' => 'Ngành Truyền thông đa phương tiện',
                'anh_dai_dien' => 'https://mighty.tools/mockmind-api/content/human/117.jpg',
                'khoa_id' => 3,
                'trang_thai' => 1,
            ],
            [
                'ho_va_ten' => 'Trần Văn R',
                'can_cuoc' => '036680204742',
                'ma_sinh_vien' => 'SV0018',
                'email' => 'tranvanr@example.com',
                'password' => Hash::make('88888888'),
                'so_dien_thoai' => '0934567890',
                'thong_tin_chung' => 'Ngành Kỹ thuật phần mềm',
                'anh_dai_dien' => 'https://mighty.tools/mockmind-api/content/human/118.jpg',
                'khoa_id' => 4,
                'trang_thai' => 1,
            ],
        ]);
    }
}
